### ISSUE TITLE
Changes over the web page

### ISSUE THREAD

**Issue by dachafra** [OEG-DataIntegration/GenQueVKG#2]
- Mismo tamaño de letra en introducción y audience
- Quitar fechas en las sesiones
- Poner email de cada organizer y una foto
- Cambiar descripción de Andrea (está helio)
- Logos para las tecnologías (en vez del nombre)
- Frase de resumen de cada una de las herramientas que presentamos.
- Imagen de OEG transparente
- Link a Open Summer of Code web: http://summerofcode.oeg-upm.net/

**Comment by AndreaCimminoArriaga** [comment]
* Mismo tamaño de letra en introducción y audience (DONE)
* Quitar fechas en las sesiones (DONE)
* Poner email de cada organizer y una foto (DONE)
* Cambiar descripción de Andrea (está helio) (DONE)
* Logos para las tecnologías (en vez del nombre) (DONE)
* Frase de resumen de cada una de las herramientas que presentamos.
* Imagen de OEG transparente (PROCESSED)
* Link a Open Summer of Code web: http://summerofcode.oeg-upm.net/ (DONE)
